### ISSUE TITLE
The Validators link in the documentation has a broken page link. 

### ISSUE THREAD

**Issue by hex-aragon** [initia-labs/initia#146]
**Describe the bug**

The link https://github.com/initia-labs/initia?tab=readme-ov-file#documentation의 validator is broken. Please fix it. 

**To Reproduce**
1. Go to 'https://github.com/initia-labs/initia?tab=readme-ov-file#documentation'
2. Click on 'Validators'
3. Go to https://docs.initia.xyz/5rqmievvbpigqonnsuwk/run-initia-node/running-initia-node로 and see “Page not found”.  

**Expected behavior**
https://docs.initia.xyz/5rqmievvbpigqonnsuwk/run-initia-node/running-initia-node에서 initia node should show the documentation to be operational. 

**Screenshots**
![스크린샷 2024-05-15 00-20-49](https://github.com/initia-labs/initia/assets/152189794/e09402ec-eeff-41a9-b23f-608d738ed1a4)

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] : Ubuntu22
 - Browser [e.g. chrome, safari] Brave

**Smartphone (please complete the following information):**

**Additional context**
I read the official documentation and was curious, so I clicked on Validator, but I found the error as shown in the captured photo. Please fix it~~.

**Comment by Vritra4** [comment]
seems working now

**Comment by Vritra4** [comment]
closed due to inactivity. please feel free to reopen it if you are still having the problem :)
