### ISSUE TITLE
Clicking the 'return to home' button after completion of task 1 faucet does not return to home

### ISSUE THREAD

**Issue by kurohoan** [initia-labs/initia#149]
Clicking the 'return to home' button after completion of task 1 faucet does not return to home

Relevant page.
https://faucet.testnet.initia.xyz/?address=

Cause: The link is not set.
![2024-05-15 10_47_21-Initia Faucet](https://github.com/initia-labs/initia/assets/60129053/ce1fc369-7b54-457b-b231-50a02566013e)

**Comment by beer-1** [comment]
This is not chain related issue.

**Comment by kurohoan** [comment]
Then tell me where I can report bugs on the testnet.
