### ISSUE TITLE
The attached error occurs on the page to set the password after installing the initia wallet.

### ISSUE THREAD

**Issue by kurohoan** [initia-labs/initia#150]
The attached error occurs on the page to set the password after installing the initia wallet.
![2024-05-15 10_50_25-検索](https://github.com/initia-labs/initia/assets/60129053/3eaae212-dcd1-46f0-b3a1-11e63186acf8)

execution environment
OS: Windows 11
Browser: Chrome 124.0.6367.203 (Official Build) (64-bit)

Provides some errors that were occurring in the JS console.
![2024-05-15 10_58_56-スタート](https://github.com/initia-labs/initia/assets/60129053/a7403931-5805-49b3-913c-011c511938b2)
![2024-05-15 10_59_33-スタート](https://github.com/initia-labs/initia/assets/60129053/4c13e819-8164-456d-883d-cf73d518c114)

**Comment by beer-1** [comment]
This is not chain related issue.

**Comment by kurohoan** [comment]
Then tell me where I can report bugs on the testnet.
