### ISSUE TITLE
When the user is transferred to My Page after completing the swap, the pre-swap balance is displayed.

### ISSUE THREAD

**Issue by kurohoan** [initia-labs/initia#151]
After completing the swap, the user is prompted to go to the my page, but when they go to the my page, the balance before the swap is displayed.
This is the case even if the transition is made after the transaction has been completed, the pre-swap balance is displayed in the same way, and the balance is displayed after the swap when the page is reloaded.

![2024-05-15 11_04_05-スタート](https://github.com/initia-labs/initia/assets/60129053/92d56089-6158-462b-b135-f0ce3a1cd676)

OS: Windows11
Browser: Chrome Version: 124.0.6367.203 (Official Build) (64-bit)

**Comment by beer-1** [comment]
This is not chain related issue.

**Comment by kurohoan** [comment]
Then tell me where I can report bugs on the testnet.
