### ISSUE TITLE
initia wallet

### ISSUE THREAD

**Issue by rishi95122** [initia-labs/initia#156]
i don't know if this is the bug or timer set buy you.
but initia wallet getting logout after every 30secs - 1min span ,this is really disturbing experience while performing testnet

**Desktop (please complete the following information):**
 - OS: [windows 11]
 - Browser [chrome]
 - Version [latest]

**Comment by BootcampZero** [comment]
Surely this needs to be removed

**Comment by beer-1** [comment]
This is not chain related issue.

but yea we know this issue and seems fixed in new wallet extension. so please check the updates.
