### ISSUE TITLE
SWAP DEFAULT

### ISSUE THREAD

**Issue by philip0529** [initia-labs/initia#160]
As I undergo with the testnet, I found the swapping area a bit hassle.
Typically, every NATIVE Token from a certain project used to be a default token in the upper portion of the swap
![image](https://github.com/initia-labs/initia/assets/61023242/e1450b52-a94d-49e4-8295-85accb8105d8)

I believe changing it to INITT as default upper portion of the swap will have a better look.
![image](https://github.com/initia-labs/initia/assets/61023242/11e2ac12-ae06-4f7b-a03e-5885fa980211)

Thanks

**Comment by beer-1** [comment]
This is not chain related issue.
