### ISSUE TITLE
Add permanent Auto-lock timer

### ISSUE THREAD

**Issue by razil5** [initia-labs/initia#161]
**Describe the solution you'd like**
Add the option of being able to set the permanent auto-lock to prevent the wallet from disconnecting

**Comment by simcheolhwan** [comment]
The latest version of the wallet extension has resolved this.

1. Go to Extensions: Click the three dots (menu) > `More tools` > `Extensions`.
2. Enable Developer Mode: Toggle `Developer mode` on (top-right corner).
3. Click Update: Press the `Update` button to refresh all extensions.
