### ISSUE TITLE
Cannot use initiad snapshots commands while node is running

### ISSUE THREAD

**Issue by 0x4r45h** [initia-labs/initia#165]
**Describe the bug**
When a node is running, executing `initiad snapshots` sub-commands like `list` returns this error:    
`Error: failed to initialize database: resource temporarily unavailable`    

But if you stop the node, it works as expected.     
**To Reproduce**
1. Run a node with `initiad start`
2. Run `initiad snapshots list`

**Expected behavior**
It should work whether node is running or not

**Environment**
 - OS: Running inside Docker container, the base image is Debian GNU/Linux 12 (bookworm)
 - Initiad Version v0.2.14

**Additional Context**
I've set ulimits nofile to 65535 for my docker containers, but didn't increase them on the host system.      
could it be root cause of problem? 🤔

**Comment by Vritra4** [comment]
It's normal. `snapshots` command can be run only when the node is not running :)
