### ISSUE TITLE
Invalid address on chain

### ISSUE THREAD

**Issue by TuanTQ15** [initia-labs/initia#173]
I did the faucet, and someone pushed the address value is "64" but it still passed validation on the FE. The transaction failed, please add the validation before data goes to the network
https://scan.testnet.initia.xyz/initiation-1/accounts/init160k7l0luwlpgs39wxw849guzzhzrcn8uk7pavs/txs

**Comment by TuanTQ15** [comment]
<img width="478" alt="image" src="https://github.com/initia-labs/initia/assets/83053023/a63414b3-4d06-48a9-bd29-e5b516755c73">

**Comment by beer-1** [comment]
Thanks for reporting!
and we added validation on faucet :)
