### ISSUE TITLE
Make wallet to avoid asking for passwords too often

### ISSUE THREAD

**Issue by ikbalnodex** [initia-labs/initia#174]
![image](https://github.com/initia-labs/initia/assets/119092888/449905cd-4a69-499a-a4cf-1edc8b478516)
The wallet extension asks for the password too much, a little annoying for me, when I switch tabs, the extension asks me again to enter the password.

I hope this extension is updated to ask for the password only when we close the software itself, whether Edge, Chrome, or something else.

**Comment by KonstantinLitvin** [comment]
You could change auto-lock time in settings
Agree, default value could be a bit bigger like in MetaMask

**Comment by BernardoRM188** [comment]
i share the same pain point

**Comment by Vritra4** [comment]
already fixed afaik: update the extension please

**Comment by simcheolhwan** [comment]
Duplicated #161
