### ISSUE TITLE
Block 221684 error

### ISSUE THREAD

**Issue by hiepntnaa** [initia-labs/initia#178]
5:40PM INF received complete proposal block hash=2D393CA1E4D9A3F615E11D7EABD745B132657797AA1E0E9D468DE72AB4019DC5 height=221684 module=consensus
5:40PM ERR CONSENSUS FAILURE!!! err="+2/3 committed an invalid block: don't have header #216143" module=consensus stack="goroutine 840 [running]:\nruntime/debug.Stack()\n\truntime/debug/stack.go:24 +0x5e\ngithub.com/cometbft/cometbft/consensus.(State).receiveRoutine.func2()\n\tgithub.com/cometbft/cometbft@v0.38.7/consensus/state.go:801 +0x46\npanic({0x2fea580?, 0xc06bf1c980?})\n\truntime/panic.go:770 +0x132\ngithub.com/cometbft/cometbft/consensus.(State).finalizeCommit(0xc000d00008, 0x361f4)\n\tgithub.com/cometbft/cometbft@v0.38.7/consensus/state.go:1713 +0x1045\ngithub.com/cometbft/cometbft/consensus.(State).tryFinalizeCommit(0xc000d00008, 0x361f4)\n\tgithub.com/cometbft/cometbft@v0.38.7/consensus/state.go:1682 +0x2e8\ngithub.com/cometbft/cometbft/consensus.(State).handleCompleteProposal(0xc000d00008, 0x361f4)\n\tgithub.com/cometbft/cometbft@v0.38.7/consensus/state.go:2060 +0x372\ngithub.com/cometbft/cometbft/consensus.(State).handleMsg(0xc000d00008, {{0x40ff540, 0xc0751285d0}, {0xc009893b90, 0x28}})\n\tgithub.com/cometbft/cometbft@v0.38.7/consensus/state.go:910 +0x178\ngithub.com/cometbft/cometbft/consensus.(State).receiveRoutine(0xc000d00008, 0x0)\n\tgithub.com/cometbft/cometbft@v0.38.7/consensus/state.go:836 +0x3f1\ncreated by github.com/cometbft/cometbft/consensus.(*State).OnStart in goroutine 717\n\tgithub.com/cometbft/cometbft@v0.38.7/consensus/state.go:398 +0x10c\n"
5:40PM INF service stop impl=baseWAL module=consensus msg="Stopping baseWAL service" wal=/root/.initia/data/cs.wal/wal

I got the above error. I deleted the .initia and ran it again twice but both got errors at block 221684.

**Comment by Vritra4** [comment]
rollback with `initiad rollback` and sync again please

**Comment by Vritra4** [comment]
close due to lack of response. please feel free to reopen it if you are still having the problem
