### ISSUE TITLE
Error when sync to block $221683

### ISSUE THREAD

**Issue by calucivn** [initia-labs/initia#179]
Dear dev,
I've got error when sync to block 2216383. Please kindly help to check and investigate the root cause
initiad v0.2.15
8 core 24gb ram.

`3:00PM INF Replay: BlockPart height=221684 module=consensus peer=66abd758f6971eb8227fc54d11cb56ca1ca280e6 round=0
3:00PM INF received complete proposal block hash=2D393CA1E4D9A3F615E11D7EABD745B132657797AA1E0E9D468DE72AB4019DC5 height=22
panic: +2/3 committed an invalid block: don't have header #216143
goroutine 725 [running]:
github.com/cometbft/cometbft/consensus.(*State).finalizeCommit(0xc001346008, 0x361f4)
        github.com/cometbft/cometbft@v0.38.7/consensus/state.go:1713 +0x1045
github.com/cometbft/cometbft/consensus.(*State).tryFinalizeCommit(0xc001346008, 0x361f4)
        github.com/cometbft/cometbft@v0.38.7/consensus/state.go:1682 +0x2e8
github.com/cometbft/cometbft/consensus.(*State).handleCompleteProposal(0xc001346008, 0x361f4)
        github.com/cometbft/cometbft@v0.38.7/consensus/state.go:2060 +0x372
github.com/cometbft/cometbft/consensus.(*State).handleMsg(0xc001346008, {{0x40ff540, 0xc00b3806d8}, {0xc002a4b9e0, 0x28}})
        github.com/cometbft/cometbft@v0.38.7/consensus/state.go:910 +0x178
github.com/cometbft/cometbft/consensus.(*State).readReplayMessage(0xc001346008, 0x349cf60?, {0x0?, 0x0?})
        github.com/cometbft/cometbft@v0.38.7/consensus/replay.go:82 +0x8b7
github.com/cometbft/cometbft/consensus.(*State).catchupReplay(0xc001346008, 0x361f4)
        github.com/cometbft/cometbft@v0.38.7/consensus/replay.go:161 +0x6cd
github.com/cometbft/cometbft/consensus.(*State).OnStart(0xc001346008)
        github.com/cometbft/cometbft@v0.38.7/consensus/state.go:343 +0x165
github.com/cometbft/cometbft/libs/service.(*BaseService).Start(0xc001346008)
        github.com/cometbft/cometbft@v0.38.7/libs/service/service.go:144 +0x2f5
github.com/cometbft/cometbft/consensus.(*Reactor).SwitchToConsensus(_, {{{0xb, 0x0}, {0xc001aa0d40, 0x6}}, {0xc001aa0d50, 0
        github.com/cometbft/cometbft@v0.38.7/consensus/reactor.go:131 +0xb9
github.com/cometbft/cometbft/blocksync.(*Reactor).poolRoutine(0xc000f345a0, 0x0)
        github.com/cometbft/cometbft@v0.38.7/blocksync/reactor.go:412 +0x1ab3
github.com/cometbft/cometbft/blocksync.(*Reactor).OnStart.func1()
        github.com/cometbft/cometbft@v0.38.7/blocksync/reactor.go:132 +0x54
created by github.com/cometbft/cometbft/blocksync.(*Reactor).OnStart in goroutine 1
        github.com/cometbft/cometbft@v0.38.7/blocksync/reactor.go:130 +0x8b
initiad.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
initiad.service: Failed with result 'exit-code'.
`

**Comment by Vritra4** [comment]
rollback with `initiad rollback` and sync again please

**Comment by Vritra4** [comment]
close due to no response
