### ISSUE TITLE
I think you should create an email reminder for feeding jennie

### ISSUE THREAD

**Issue by Mimicute101** [initia-labs/initia#198]
**Is your feature request related to a problem? Please describe.**
A reminder through email about feeding Jennie

**Describe the solution you'd like**
If an email reminder is applied to feeding jennie most people won't forget about feeding her
**Describe alternatives you've considered**
An email reminder would really go along way to doing the testnet and feeding Jennie 

**Additional context**
Most people have many things they're handling... having an email reminder would enable everyone to keep in mind what they are supposed to do....

**Comment by Vritra4** [comment]
close this because it's not relevant to this repository: please feel free to discuss it on our [discord](https://discord.com/invite/initia). :)
