### ISSUE TITLE
Testnet issue 

### ISSUE THREAD

**Issue by emmatheo** [initia-labs/initia#201]
To claim gas token with gitcoin password being => 20 is really not fair, gitcoin score has been on of the most stressful innovation in the space ,where different protocols are being added and scores are reduced often and 20 is really high 

Solution 
Before now to get the $Gas token were about 4 gitcoin score I think that's fair enough a cirteria .

Or using an ENS domain or number of transactions on the Eth chain would be nice .

**Comment by Vritra4** [comment]
Close it because it is not about this repository. Could you visit [our discord](https://discord.com/invite/initia)? Please feel free to talk about that in the discord server.
