### ISSUE TITLE
Access to a variable that might be nill due to an error, might lead to forking

### ISSUE THREAD

**Issue by 0xVolodya** [initia-labs/initia#236]
**Describe the bug**
Access to a variable that might be nill due to an error.

**Expected behavior**
check not nill/ handle error
**Errors**
```go
	execRes, err := k.moveVM.ExecuteEntryFunction(
		types.NewVMStore(sdkCtx, k.VMStore),
		NewApi(k, sdkCtx),
		types.NewEnv(sdkCtx, ac, ec),
		gasForRuntime,
		senders,
		payload,
	)

	// consume gas first and check error
	gasMeter.ConsumeGas(execRes.GasUsed, "move runtime") // execRes can be nill, error throw
	if err != nil {
		return err
	}

```
[x/move/keeper/handler.go#L216](https://github.com/initia-labs/initia/blob/4705e2d348289cbee2ae75bda34b34574c7eacd8/x/move/keeper/handler.go#L216)

Same issues
https://github.com/initia-labs/initia/blob/4705e2d348289cbee2ae75bda34b34574c7eacd8/x/move/keeper/handler.go#L332
whole file here
https://github.com/initia-labs/initia/blob/5de38c6fa15009889a413912eb69a280b2af9606/x/slashing/keeper/params.go#L48

https://github.com/initia-labs/initia/blob/43cfa4af7923890ef9946d0e92791f3f5eff9577/x/move/keeper/api.go#L70
https://github.com/initia-labs/initia/blob/43cfa4af7923890ef9946d0e92791f3f5eff9577/x/move/keeper/api.go#L86

https://github.com/initia-labs/initia/blob/e2a08917780600395979b6149ce94fc8940d0da6/x/ibc-hooks/move-hooks/ack.go#L28
https://github.com/initia-labs/initia/blob/e2a08917780600395979b6149ce94fc8940d0da6/x/ibc-hooks/move-hooks/ack.go#L111
https://github.com/initia-labs/initia/blob/466a94129e4f250a33d973959206668fcf8fbc82/x/ibc-hooks/move-hooks/receive.go#L26

https://github.com/initia-labs/initia/blob/604075be317ac87a23008e4f5818e932a7306a85/x/ibc/nft-transfer/ibc_module.go#L200
**Additional context**

**Comment by beer-1** [comment]
Thanks for reporting! 

we changed the implementation to send gasBalance reference and use that to calculate gasUsed, so no more this issue.

Please feel free to reopen the issue if you think still there is issue.
