### ISSUE TITLE
How to start a localnet

### ISSUE THREAD

**Issue by AiDaiP** [initia-labs/initia#259]
Hi, I want to start a localnet, but the documentation doesn't seem to describe it. I tried to initialize it with `initiad init` and then start it with `initiad start`, but that didn't work.
I got this error message:
```
Error: error during handshake: error on replay: validator set is empty after InitGenesis, please ensure at least one validator is initialized with a delegation greater than or equal to the DefaultPowerReduction ({824644800576})
```
This seems to be due to missing necessary configuration steps for localnet. I found a similar problem in #182 . The missing step seems to be called `genTx`, but I didn't find the relevant configuration documentation.
Can you provide some information on configuring localnet? Thanks.

**Comment by turingH** [comment]
I have the same problem

**Comment by AiDaiP** [comment]
Hello, thanks for your reply. I tried to run the script you provided using v0.4.4 in release, and the previous error no longer appeared.
But it keeps outputting this error. Is this correct? 
```
4:07PM ERR recovered from panic in ExtendVoteHandler err="runtime error: invalid memory address or nil pointer dereference" module=server
4:07PM ERR failed to extend vote err="panic: runtime error: invalid memory address or nil pointer dereference" hash=79134DBD991B97A1DA51D0AE5BD10017C9051449DFA17FCBF47D80DEE50AF0DC height=7 module=server
```
The result of querying status using `initiad` is:
```
initiad status
{"node_info":{"protocol_version":{"p2p":"8","block":"11","app":"0"},"id":"4ecec93a335f5a0019316bf32caf89353a36dbaf","listen_addr":"tcp://0.0.0.0:26656","network":"local-initia","version":"0.38.10","channels":"40202122233038606100","moniker":"local-initia","other":{"tx_index":"on","rpc_address":"tcp://127.0.0.1:26657"}},"sync_info":{"latest_block_hash":"","latest_app_hash":"","latest_block_height":"0","latest_block_time":"1970-01-01T00:00:00Z","earliest_block_hash":"","earliest_app_hash":"","earliest_block_height":"0","earliest_block_time":"1970-01-01T00:00:00Z","catching_up":false},"validator_info":{"address":"790373B27F25ADDA80E4D22F715E428C7A9FD0EE","pub_key":{"type":"tendermint/PubKeyEd25519","value":"xnYjT9hGnPxw+k+MmgNlS+rVPz193EZciTZv/1UH+/g="},"voting_power":"100000000"}}
```

**Comment by AiDaiP** [comment]
Thank you very much, I successfully ran the validator in the latest version (v0.4.7) using your script. I tried to perform some contract deployments and successfully deployed the move contract in initia-tutorials, which should indicate that everything is working properly. Your script helped me a lot, thank you again.
