### ISSUE TITLE
Website buttons not working

### ISSUE THREAD

**Issue by tudorpintea999** [initia-labs/initia#327]
Hello team
The buttons under "Applications" section are not working except the faucet one, tried to find the repo to fix the urls but i didnt find it .
Merry Christmas 
<img width="1410" alt="Screenshot 2024-12-24 at 01 10 13" src="https://github.com/user-attachments/assets/d662cdfb-0963-4c0b-9e1e-f427d22fa2e4" />

**Comment by beer-1** [comment]
Hey @tudorpintea999,  thanks for your report. but I think scrolling itself is the intended action in the website and seems it is working well. 

Please reopen it if you have still seeing the issue!
